version: '3.1'

services:
  postgresdb:
    container_name: postgresdb2
    image: postgres:13.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    volumes:
      - bank-pgsql-data:/var/lib/postgresql/data
    networks:
      - docker_network

  bank-api:
    container_name: bank-api
    image: trebor006/bank-api:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - docker_network
    depends_on:
      - postgresdb

networks:
  docker_network:
    driver: bridge

volumes:
  bank-pgsql-data:
